export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const SORT_PRODUCT = "SORT_PRODUCT";
export const FILTERED_PRODUCTS = "FILTERED_PRODUCTS";
export const UPDATE_CART = "UPDATE_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const SEARCH_UPDATE = "SEARCH_UPDATE"